version: '3.5'
services:

  demo-web-server:
    image: nginx:latest
    container_name: demo-web-server
    restart: always
    volumes:
      - ./web-server/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - demo-fiber-mysql-gorm
    ports:
      - 80:80

  demo-fiber-mysql-gorm:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: demo-fiber-mysql-gorm
    restart: always
    ports:
      - 3000:3000

volumes:
  demo-fiber-gorm-datavolume:

networks:
  default:
    external: 
      name: demo-network



# docker run --name=mysql_demo -e MYSQL_ROOT_PASSWORD=#demo#MySQL -e MYSQL_DATABASE=demoMySQL -p 3306:3306 -d mysql

# CREATE TABLE Persons (
#     PersonID int,
#     LastName varchar(255),
#     FirstName varchar(255),
#     Address varchar(255),
#     City varchar(255)
# );
